#!/usr/bin/env python3
"""Train/evaluate a tree-based match outcome model from engineered SQLite features."""

from __future__ import annotations

import argparse
import json
import pickle
import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import numpy as np

try:
    from sklearn.metrics import accuracy_score, f1_score, log_loss, precision_score, recall_score, roc_auc_score
    from sklearn.tree import DecisionTreeClassifier
except ImportError as exc:  # pragma: no cover
    raise SystemExit(
        "scikit-learn is required for modeling. Install with: pip install scikit-learn"
    ) from exc


ID_COLUMNS = {"match_id", "match_date", "surface", "player_id", "opponent_id"}
TARGET_COLUMN = "is_winner"
DEFAULT_MODEL_DIR = Path("data/models")


@dataclass
class Dataset:
    feature_columns: List[str]
    x: np.ndarray
    y: np.ndarray
    seasons: np.ndarray
    surfaces: np.ndarray


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--sqlite-path",
        type=Path,
        default=Path("data/features/player_features.sqlite"),
        help="SQLite artifact generated by pipeline/features.py.",
    )
    parser.add_argument(
        "--model-dir",
        type=Path,
        default=DEFAULT_MODEL_DIR,
        help="Directory where model and evaluation artifacts are written.",
    )
    parser.add_argument("--table", default="player_features", help="Source SQLite table.")
    parser.add_argument("--max-depth", type=int, default=6)
    parser.add_argument("--min-samples-leaf", type=int, default=120)
    parser.add_argument("--top-paths", type=int, default=8)
    return parser.parse_args()


def _connect(sqlite_path: Path) -> sqlite3.Connection:
    if not sqlite_path.exists():
        raise SystemExit(f"SQLite file not found: {sqlite_path}")
    conn = sqlite3.connect(sqlite_path)
    conn.row_factory = sqlite3.Row
    return conn


def _feature_columns(conn: sqlite3.Connection, table: str) -> List[str]:
    rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
    names = [str(row[1]) for row in rows]
    return [c for c in names if c not in ID_COLUMNS and c != TARGET_COLUMN]


def load_dataset(sqlite_path: Path, table: str) -> Dataset:
    with _connect(sqlite_path) as conn:
        feature_columns = _feature_columns(conn, table)
        sql = f'''
            SELECT event_year, surface, {TARGET_COLUMN}, {', '.join(f'"{c}"' for c in feature_columns)}
            FROM {table}
            WHERE {TARGET_COLUMN} IS NOT NULL
            ORDER BY match_date ASC
        '''
        rows = conn.execute(sql).fetchall()

    if not rows:
        raise SystemExit("No rows found in SQLite feature table.")

    x_rows: List[List[float]] = []
    y: List[int] = []
    seasons: List[int] = []
    surfaces: List[str] = []
    for row in rows:
        x_rows.append([float(row[c]) if row[c] is not None else np.nan for c in feature_columns])
        y.append(int(row[TARGET_COLUMN]))
        seasons.append(int(row["event_year"]))
        surfaces.append(str(row["surface"] or "Unknown"))

    return Dataset(
        feature_columns=feature_columns,
        x=np.asarray(x_rows, dtype=np.float64),
        y=np.asarray(y, dtype=np.int64),
        seasons=np.asarray(seasons, dtype=np.int64),
        surfaces=np.asarray(surfaces, dtype=object),
    )


def _split_by_season(seasons: np.ndarray) -> Tuple[np.ndarray, np.ndarray, int]:
    unique = sorted(int(x) for x in np.unique(seasons))
    holdout_year = unique[-1]
    if len(unique) < 2:
        rng = np.random.default_rng(42)
        idx = np.arange(len(seasons))
        rng.shuffle(idx)
        split = int(len(idx) * 0.8)
        return idx[:split], idx[split:], holdout_year

    train_idx = np.where(seasons < holdout_year)[0]
    test_idx = np.where(seasons == holdout_year)[0]
    if len(test_idx) == 0 or len(train_idx) == 0:
        idx = np.arange(len(seasons))
        split = int(len(idx) * 0.8)
        return idx[:split], idx[split:], holdout_year
    return train_idx, test_idx, holdout_year


def _imputer_stats(x_train: np.ndarray) -> np.ndarray:
    medians = np.nanmedian(x_train, axis=0)
    medians = np.where(np.isnan(medians), 0.0, medians)
    return medians.astype(np.float64)


def _apply_imputer(x: np.ndarray, medians: np.ndarray) -> np.ndarray:
    out = np.array(x, copy=True)
    inds = np.where(np.isnan(out))
    out[inds] = medians[inds[1]]
    return out


def _metrics(y_true: np.ndarray, y_pred: np.ndarray, y_prob: np.ndarray) -> Dict[str, Optional[float]]:
    payload: Dict[str, Optional[float]] = {
        "count": float(len(y_true)),
        "accuracy": float(accuracy_score(y_true, y_pred)),
        "precision": float(precision_score(y_true, y_pred, zero_division=0)),
        "recall": float(recall_score(y_true, y_pred, zero_division=0)),
        "f1": float(f1_score(y_true, y_pred, zero_division=0)),
    }
    try:
        payload["roc_auc"] = float(roc_auc_score(y_true, y_prob))
    except ValueError:
        payload["roc_auc"] = None
    try:
        payload["log_loss"] = float(log_loss(y_true, np.column_stack([1.0 - y_prob, y_prob]), labels=[0, 1]))
    except ValueError:
        payload["log_loss"] = None
    return payload


def _path_rules(model: DecisionTreeClassifier, feature_columns: Sequence[str], top_n: int) -> List[Dict[str, Any]]:
    tree = model.tree_
    children_left = tree.children_left
    children_right = tree.children_right
    feature = tree.feature
    threshold = tree.threshold
    value = tree.value[:, 0, :]
    samples = tree.n_node_samples

    leaves: List[Tuple[int, List[Dict[str, Any]]]] = []

    def walk(node_id: int, rules: List[Dict[str, Any]]) -> None:
        if children_left[node_id] == children_right[node_id]:
            leaves.append((node_id, list(rules)))
            return
        fidx = int(feature[node_id])
        fname = feature_columns[fidx]
        thr = float(threshold[node_id])

        left_rule = {"feature": fname, "operator": "<=", "threshold": thr}
        rules.append(left_rule)
        walk(int(children_left[node_id]), rules)
        rules.pop()

        right_rule = {"feature": fname, "operator": ">", "threshold": thr}
        rules.append(right_rule)
        walk(int(children_right[node_id]), rules)
        rules.pop()

    walk(0, [])

    ranked = sorted(leaves, key=lambda x: int(samples[x[0]]), reverse=True)[:top_n]
    results: List[Dict[str, Any]] = []
    for node_id, rules in ranked:
        counts = value[node_id]
        total = float(np.sum(counts))
        win_prob = float(counts[1] / total) if total else 0.5
        results.append(
            {
                "leaf_id": int(node_id),
                "sample_count": int(samples[node_id]),
                "predicted_class": int(np.argmax(counts)),
                "win_probability": win_prob,
                "rules": rules,
            }
        )
    return results


def _group_metrics(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    y_prob: np.ndarray,
    seasons: np.ndarray,
    surfaces: np.ndarray,
) -> Dict[str, Dict[str, Dict[str, Optional[float]]]]:
    by_season: Dict[str, Dict[str, Optional[float]]] = {}
    for season in sorted(set(int(s) for s in seasons.tolist())):
        idx = np.where(seasons == season)[0]
        if len(idx) < 25:
            continue
        by_season[str(season)] = _metrics(y_true[idx], y_pred[idx], y_prob[idx])

    by_surface: Dict[str, Dict[str, Optional[float]]] = {}
    for surface in sorted(set(str(s) for s in surfaces.tolist())):
        idx = np.where(surfaces == surface)[0]
        if len(idx) < 25:
            continue
        by_surface[surface] = _metrics(y_true[idx], y_pred[idx], y_prob[idx])

    by_season_surface: Dict[str, Dict[str, Optional[float]]] = {}
    for season in sorted(set(int(s) for s in seasons.tolist())):
        for surface in sorted(set(str(s) for s in surfaces.tolist())):
            idx = np.where((seasons == season) & (surfaces == surface))[0]
            if len(idx) < 25:
                continue
            by_season_surface[f"{season}__{surface}"] = _metrics(y_true[idx], y_pred[idx], y_prob[idx])

    return {
        "by_season": by_season,
        "by_surface": by_surface,
        "by_season_surface": by_season_surface,
    }


def train_and_export(args: argparse.Namespace) -> Dict[str, Any]:
    data = load_dataset(args.sqlite_path, args.table)
    train_idx, test_idx, holdout_year = _split_by_season(data.seasons)

    x_train_raw = data.x[train_idx]
    x_test_raw = data.x[test_idx]
    y_train = data.y[train_idx]
    y_test = data.y[test_idx]

    medians = _imputer_stats(x_train_raw)
    x_train = _apply_imputer(x_train_raw, medians)
    x_test = _apply_imputer(x_test_raw, medians)

    model = DecisionTreeClassifier(
        max_depth=args.max_depth,
        min_samples_leaf=args.min_samples_leaf,
        random_state=42,
        class_weight="balanced",
    )
    model.fit(x_train, y_train)

    prob_test = model.predict_proba(x_test)[:, 1]
    pred_test = (prob_test >= 0.5).astype(np.int64)

    feature_importance = sorted(
        [
            {"feature": name, "importance": float(score)}
            for name, score in zip(data.feature_columns, model.feature_importances_.tolist())
            if score > 0.0
        ],
        key=lambda x: x["importance"],
        reverse=True,
    )

    evaluation = {
        "split": {
            "holdout_year": int(holdout_year),
            "train_rows": int(len(train_idx)),
            "test_rows": int(len(test_idx)),
        },
        "overall": _metrics(y_test, pred_test, prob_test),
        "segments": _group_metrics(
            y_test,
            pred_test,
            prob_test,
            data.seasons[test_idx],
            data.surfaces[test_idx],
        ),
    }

    top_paths = _path_rules(model, data.feature_columns, args.top_paths)

    model_payload = {
        "trained_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "model_type": "DecisionTreeClassifier",
        "feature_columns": data.feature_columns,
        "imputer_medians": medians.tolist(),
        "threshold": 0.5,
        "model": model,
    }

    args.model_dir.mkdir(parents=True, exist_ok=True)
    model_path = args.model_dir / "match_outcome_tree.pkl"
    feature_path = args.model_dir / "feature_importance.json"
    paths_path = args.model_dir / "top_decision_paths.json"
    eval_path = args.model_dir / "evaluation_metrics.json"

    with model_path.open("wb") as fh:
        pickle.dump(model_payload, fh)
    feature_path.write_text(json.dumps(feature_importance, indent=2) + "\n")
    paths_path.write_text(json.dumps(top_paths, indent=2) + "\n")
    eval_path.write_text(json.dumps(evaluation, indent=2) + "\n")

    return {
        "model_artifact": str(model_path),
        "feature_importance": str(feature_path),
        "top_decision_paths": str(paths_path),
        "evaluation_metrics": str(eval_path),
        "holdout_year": int(holdout_year),
    }


def main() -> int:
    args = parse_args()
    result = train_and_export(args)
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
